apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary
  name: canary
  namespace: demo-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      hostname: canary
      containers:
        - image: harbor.apps-contour.awstmc.sschmidt.ch/demos/blue-green-canary:0.2
          name: canary
          env:
          - name: BACKGROUND_COLOR
            value: "violet"
          - name: SPRING_APPLICATION_NAME
            value: "canary"
