apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-server
  name: eureka-server
  namespace: demo-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - image: harbor.apps-contour.awstmc.sschmidt.ch/demos/eureka-server:0.6
          name: eureka-server