apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: demo-eureka
spec:
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    app: eureka-server
  type: ClusterIP